name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Source
        uses: actions/checkout@v2
      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Type check
        run: |
          mypy browser      
      - name: Tests
        run: |
          INTEGRATION_TESTS=1 coverage run -m pytest browser -v
          coverage report